

- hosts: all
  gather_facts: True
  tasks:
    - name: dns_proxy connect
      include_role:
        name: "hadi2f244.free_me.dns_proxy"
      vars:
        connected: true
        dnsproxy_dns_1: "{{ freeme_dns_proxy.dnsproxy_dns_1 }}"
        dnsproxy_dns_2: "{{ freeme_dns_proxy.dnsproxy_dns_2 }}"