
- hosts: all
  gather_facts: True
  tasks:
    - name: v2ray disconnect
      include_role:
        name: "hadi2f244.free_me.v2ray"
      vars:
        connected: false
        set_env_proxy: true
        set_apt_proxy: true
        set_container_proxy: true
        v2ray_addr: "{{ freeme.v2ray.v2ray_addr }}"
        v2ray_port: "{{ freeme.v2ray.v2ray_port }}"
        v2ray_uuid: "{{ freeme.v2ray.v2ray_uuid }}"
        proxy_socks_port: "{{ freeme.v2ray.proxy_socks_port }}"
        proxy_http_port: "{{ freeme.v2ray.proxy_http_port }}"
      when: freeme.use_freeme == true
