

- hosts: all
  gather_facts: True
  tasks:
    - name: container_proxy disconnect
      include_role:
        name: "hadi2f244.free_me.container_proxy"
      vars:
        connected: false
        http_proxy: "{{ freeme_container_proxy.http_proxy }}"
        https_proxy: "{{ freeme_container_proxy.https_proxy }}"