

- hosts: all
  gather_facts: True
  tasks:
    - name: apt_proxy disconnect
      include_role:
        name: "hadi2f244.free_me.apt_proxy"
      vars:
        connected: false
        http_proxy: "{{ freeme_apt_proxy.http_proxy }}"
        https_proxy: "{{ freeme_apt_proxy.https_proxy }}"
      when: use_freeme == true
