

- hosts: all
  gather_facts: True
  tasks:
    - name: env_proxy disconnect
      include_role:
        name: "hadi2f244.free_me.env_proxy"
      vars:
        connected: false
        http_proxy: "{{ freeme.env_proxy.http_proxy }}"
        https_proxy: "{{ freeme.env_proxy.https_proxy }}"
      when: freeme.use_freeme == true
